import DimensionalCompactificationQuantumFieldTheoryLemmaCanonicalLaneLean.EffectiveFieldTheoryLayer
import DimensionalCompactificationQuantumFieldTheoryLemmaCanonicalLaneLean.BridgeLemmas
import DimensionalCompactificationQuantumFieldTheoryLemmaCanonicalLaneLean.GateLemmas

namespace HautevilleHouse
namespace DimensionalCompactificationQuantumFieldTheoryLemmaCanonicalLaneLean

def ConstrainedCompactificationClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_compactification_endgame (A : AdmissibleClass) :
    ConstrainedCompactificationClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end DimensionalCompactificationQuantumFieldTheoryLemmaCanonicalLaneLean
end HautevilleHouse